import { Link } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import { projectRepository } from '@/db/repositories/project-repository'
import { activityRepository } from '@/db/repositories/activity-repository'
import { financeRepository } from '@/db/repositories/finance-repository'
import { formatMoney } from '@/lib/money'
import type { Project } from '@/domain/project/types'

export function HomePage() {
  const [data, setData] = useState({ active: [] as Project[], today: 0, outstanding: 0, received: 0, due: [] as Project[] })
  useEffect(() => { void (async () => { const [projects, activities, invoices, payments] = await Promise.all([projectRepository.getAll(), activityRepository.getToday(), financeRepository.getInvoices(), financeRepository.getPayments()]); const billed = invoices.filter((item) => item.status !== 'void').reduce((sum, item) => sum + item.total, 0); const received = payments.reduce((sum, item) => sum + item.amount, 0); const limit = new Date(); limit.setDate(limit.getDate() + 7); setData({ active: projects.filter((item) => item.status === 'active'), today: activities.length, outstanding: billed - received, received, due: projects.filter((item) => item.plannedEndDate && new Date(item.plannedEndDate) <= limit && item.status !== 'completed' && item.status !== 'delivered') }) })() }, [])
  const metrics = [['پروژه فعال', String(data.active.length), 'bg-indigo-600'], ['فعالیت امروز', String(data.today), 'bg-sky-600'], ['ماندهٔ دریافت', formatMoney(data.outstanding), 'bg-amber-500'], ['دریافتی', formatMoney(data.received), 'bg-emerald-600']]
  return <div className="space-y-6"><section className="overflow-hidden rounded-3xl bg-gradient-to-l from-slate-900 via-slate-800 to-indigo-900 p-6 text-white"><p className="text-sm text-indigo-200">پنل عملیاتی</p><h2 className="mt-1 text-2xl font-bold">خوش آمدید، آمادهٔ مدیریت امروز هستید.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-300">یک نمای شفاف از پروژه‌ها، جریان نقدی و کارهای فوری؛ همه‌چیز روی همین دستگاه و بدون نیاز به اینترنت ذخیره می‌شود.</p><div className="mt-5 flex flex-wrap gap-2"><Link to="/projects/new" className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-900">پروژه جدید</Link><Link to="/finance" className="rounded-xl border border-white/30 px-4 py-2 text-sm">ثبت مالی</Link></div></section><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, value, color]) => <div key={label} className={`${color} rounded-2xl p-5 text-white shadow-sm`}><p className="text-xs text-white/70">{label}</p><p className="mt-3 text-xl font-bold">{value}</p></div>)}</section><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><h3 className="font-bold">پروژه‌های فعال</h3><Link to="/projects" className="text-sm text-indigo-600">همه پروژه‌ها</Link></div><div className="mt-4 space-y-3">{data.active.length === 0 ? <p className="text-sm text-slate-500">پروژه فعالی ندارید.</p> : data.active.slice(0, 4).map((item) => <Link key={item.id} to="/projects/$projectId" params={{ projectId: item.id }} className="block rounded-xl bg-slate-50 p-3 hover:bg-slate-100"><b className="text-sm">{item.title}</b><p className="mt-1 text-xs text-slate-500">{item.workType || 'بدون نوع کار'}{item.plannedEndDate ? ` · پایان ${item.plannedEndDate}` : ''}</p></Link>)}</div></section><section className="rounded-2xl border bg-white p-5"><h3 className="font-bold">یادآوری‌ها</h3><div className="mt-4 space-y-3">{data.due.length === 0 ? <p className="text-sm text-slate-500">برای هفت روز آینده مورد فوری ندارید.</p> : data.due.map((item) => <div key={item.id} className="rounded-xl border-r-4 border-amber-400 bg-amber-50 p-3 text-sm"><b>{item.title}</b><p className="mt-1 text-xs text-amber-800">موعد برنامه‌ریزی‌شده: {item.plannedEndDate}</p></div>)}</div><Link to="/reports" className="mt-5 inline-block text-sm text-indigo-600">گزارش‌ها و بکاپ ←</Link></section></div></div>
}
