import { Link } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import { liveQuery } from 'dexie'
import { projectRepository } from '@/db/repositories/project-repository'
import { customerRepository } from '@/db/repositories/customer-repository'
import { activityRepository } from '@/db/repositories/activity-repository'
import { financeRepository } from '@/db/repositories/finance-repository'
import { reminderRepository } from '@/db/repositories/reminder-repository'
import { formatMoney } from '@/lib/money'
import { formatDateFa, toISODate } from '@/lib/dates'
import { dashboardStatuses, projectStatusLabels, executionDeadlineStatuses } from '@/domain/project/status'
import type { Project } from '@/domain/project/types'
import type { Reminder } from '@/domain/reminder/types'

export function HomePage() {
  const [data, setData] = useState({ projects: [] as Project[], customers: {} as Record<string, string>, today: 0, outstanding: 0, received: 0, reminders: [] as Reminder[] })
  const [error, setError] = useState('')
  useEffect(() => {
    const subscription = liveQuery(async () => Promise.all([projectRepository.getAll(), activityRepository.getToday(), financeRepository.getInvoices(), financeRepository.getPayments(), reminderRepository.getOpen(), customerRepository.getAll()])).subscribe({
      next: ([projects, activities, invoices, payments, reminders, customers]) => {
        const billed = invoices.filter((item) => item.status !== 'void').reduce((sum, item) => sum + item.total, 0)
        const received = payments.reduce((sum, item) => sum + item.amount, 0)
        setData({ projects, today: activities.length, outstanding: billed - received, received, reminders, customers: Object.fromEntries(customers.map((item) => [item.id, item.name])) })
      }, error: () => setError('بارگذاری داشبورد ناموفق بود.'),
    })
    return () => subscription.unsubscribe()
  }, [])
  const limit = new Date(); limit.setDate(limit.getDate() + 7)
  const due = data.projects.filter((item) => item.plannedEndDate && item.plannedEndDate <= toISODate(limit) && executionDeadlineStatuses.includes(item.status))
  const colors = ['bg-slate-600', 'bg-sky-600', 'bg-indigo-600', 'bg-amber-600', 'bg-emerald-600']
  return <div className="space-y-6 max-sm:space-y-3">
    <section data-dashboard-hero className="rounded-3xl bg-gradient-to-l from-slate-900 to-indigo-900 p-6 text-white max-sm:rounded-[20px] max-sm:p-3.5"><p className="text-sm text-indigo-200 max-sm:text-xs">پنل عملیاتی</p><h2 className="mt-1 text-2xl font-bold max-sm:text-xl max-sm:leading-7">مدیریت پروژه‌ها و کارهای امروز</h2><div className="mt-5 flex flex-wrap gap-2 max-sm:mt-3 max-sm:grid max-sm:grid-cols-3"><Link to="/projects/new" className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-900 max-sm:flex max-sm:min-h-11 max-sm:items-center max-sm:justify-center max-sm:px-2 max-sm:text-[13px]">پروژه جدید</Link><Link to="/activities/today" className="rounded-xl border border-white/30 px-4 py-2 text-sm max-sm:flex max-sm:min-h-11 max-sm:items-center max-sm:justify-center max-sm:px-2 max-sm:text-[13px]">ثبت فعالیت</Link><Link to="/finance" className="rounded-xl border border-white/30 px-4 py-2 text-sm max-sm:flex max-sm:min-h-11 max-sm:items-center max-sm:justify-center max-sm:px-2 max-sm:text-[13px]">ثبت مالی</Link></div></section>
    {error && <p role="alert" className="text-rose-700">{error}</p>}
    {data.projects.some((item) => item.status === 'active') && <section className="space-y-2 rounded-2xl border border-amber-300 bg-amber-50 p-4"><h3 className="font-bold">بررسی پروژه‌های فعال قدیمی</h3><p className="text-sm">برای هر پروژه مشخص کنید اجرا شروع شده یا هنوز در مرحله برنامه‌ریزی است.</p>{data.projects.filter((item) => item.status === 'active').map((item) => <Link key={item.id} to="/projects/$projectId" params={{ projectId: item.id }} className="block rounded-xl bg-white p-3 text-sm text-indigo-700">{item.title} — {data.customers[item.customerId] || 'مشتری نامشخص'} ← تعیین وضعیت</Link>)}</section>}
    <section aria-label="وضعیت پروژه‌ها" className="grid grid-cols-2 gap-3 lg:grid-cols-5 max-sm:grid-cols-3 max-sm:gap-2">{dashboardStatuses.map((status, index) => <Link key={status} aria-label={`پروژه‌های ${projectStatusLabels[status]}: ${data.projects.filter((item) => item.status === status).length.toLocaleString("fa-IR")}`} to="/projects" search={{ status }} className={`${colors[index]} rounded-2xl p-5 text-white shadow-sm hover:opacity-90 focus-visible:outline-2 max-sm:relative max-sm:flex max-sm:min-h-20 max-sm:flex-col max-sm:justify-between max-sm:overflow-hidden max-sm:rounded-xl max-sm:border max-sm:border-slate-200 max-sm:bg-white max-sm:p-2.5 max-sm:text-slate-800 max-sm:shadow-none`}><span aria-hidden="true" className={`hidden max-sm:absolute max-sm:inset-y-0 max-sm:right-0 max-sm:block max-sm:w-0.5 ${colors[index]}`} /><p className="text-sm max-sm:text-[11px] max-sm:leading-4"><span className="max-sm:hidden">پروژه‌های </span>{projectStatusLabels[status]}</p><p className="mt-3 text-2xl font-bold max-sm:mt-1 max-sm:text-[22px] max-sm:leading-7">{data.projects.filter((item) => item.status === status).length.toLocaleString('fa-IR')}</p><p className="mt-2 text-xs text-white/80 max-sm:hidden">مشاهده پروژه‌ها ←</p></Link>)}</section>
    <section aria-label="خلاصه امروز و مالی" className="grid gap-3 sm:grid-cols-3 max-sm:gap-0 max-sm:overflow-hidden max-sm:rounded-xl max-sm:border max-sm:border-slate-200 max-sm:bg-white max-sm:[&>a]:flex max-sm:[&>a]:min-h-11 max-sm:[&>a]:items-center max-sm:[&>a]:justify-between max-sm:[&>a]:gap-2 max-sm:[&>a]:rounded-none max-sm:[&>a]:bg-transparent max-sm:[&>a]:px-3 max-sm:[&>a]:py-2 max-sm:[&>a+a]:border-t max-sm:[&>a+a]:border-slate-100 max-sm:[&_p]:text-xs max-sm:[&_b]:min-w-0 max-sm:[&_b]:break-words max-sm:[&_b]:text-[13px]"><Link to="/activities/today" className="rounded-2xl bg-sky-50 p-5"><p className="text-sm">فعالیت امروز</p><b>{data.today.toLocaleString('fa-IR')}</b></Link><Link to="/finance" className="rounded-2xl bg-amber-50 p-5"><p className="text-sm">مانده دریافت</p><b>{formatMoney(data.outstanding)}</b></Link><Link to="/finance" className="rounded-2xl bg-emerald-50 p-5"><p className="text-sm">دریافتی</p><b>{formatMoney(data.received)}</b></Link></section>
    <section data-dashboard-projects className="space-y-3 max-sm:space-y-2"><div className="flex justify-between max-sm:items-center max-sm:gap-3 max-sm:[&>h3]:text-[15px] max-sm:[&>h3]:leading-6 max-sm:[&>a]:flex max-sm:[&>a]:min-h-11 max-sm:[&>a]:min-w-11 max-sm:[&>a]:items-center max-sm:[&>a]:justify-center"><h3 className="font-bold">پروژه‌های در انتظار، در اجرا و آمادهٔ تحویل</h3><Link to="/projects" className="text-sm text-indigo-600">همه</Link></div><div className="grid gap-3 sm:grid-cols-2 max-sm:gap-2">{data.projects.filter((item) => dashboardStatuses.includes(item.status)).map((item) => <Link key={item.id} to="/projects/$projectId" params={{ projectId: item.id }} className="block space-y-2 rounded-xl border bg-white p-4 hover:border-indigo-400 max-sm:grid max-sm:grid-cols-[minmax(0,1fr)_auto] max-sm:gap-x-2 max-sm:gap-y-1 max-sm:space-y-0 max-sm:border-slate-200 max-sm:p-3 max-sm:[&>b]:col-start-1 max-sm:[&>b]:row-start-1 max-sm:[&>b]:break-words max-sm:[&>b]:text-sm max-sm:[&>span]:col-start-2 max-sm:[&>span]:row-start-1 max-sm:[&>span]:self-start max-sm:[&>span]:text-[10px] max-sm:[&>p]:col-span-2 max-sm:[&>p]:break-words max-sm:[&>p]:text-[11px]"><b>{item.title}</b><p className="text-sm text-slate-500">{data.customers[item.customerId] || 'مشتری نامشخص'}</p><span className="inline-block rounded bg-indigo-50 px-2 py-1 text-xs text-indigo-700">{projectStatusLabels[item.status]}</span><p className="text-xs text-slate-500">تاریخ پروژه: {formatDateFa(item.startDate || item.createdAt)}</p>{item.plannedEndDate && <p className="text-xs text-slate-500">موعد پایان: {formatDateFa(item.plannedEndDate)}</p>}</Link>)}</div>{!data.projects.some((item) => dashboardStatuses.includes(item.status)) && <p className="text-sm text-slate-500">پروژه‌ای در این وضعیت‌ها ندارید.</p>}</section>
    <section className="rounded-2xl border bg-white p-5 max-sm:rounded-xl max-sm:p-3 max-sm:[&_h3]:text-[15px]"><div className="flex justify-between"><h3 className="font-bold">یادآوری‌ها و موعد پروژه‌ها</h3><Link to="/reminders" className="text-sm text-indigo-600">مدیریت</Link></div><div className="mt-4 space-y-3">{data.reminders.slice(0, 3).map((item) => <Link to="/reminders" key={item.id} className="block rounded-xl bg-amber-50 p-3 text-sm"><b>{item.title}</b><p className="mt-1 text-xs">{formatDateFa(item.dueDate)}</p></Link>)}{due.map((item) => <Link key={item.id} to="/projects/$projectId" params={{ projectId: item.id }} className="block rounded-xl bg-rose-50 p-3 text-sm"><b>{item.title}</b><p className="mt-1 text-xs">موعد پروژه: {formatDateFa(item.plannedEndDate!)}</p></Link>)}{data.reminders.length === 0 && due.length === 0 && <p className="text-sm text-slate-500">مورد فوری ندارید.</p>}</div><Link to="/calendar" className="mt-5 inline-block text-sm text-indigo-600">نمای تقویم ←</Link></section>
  </div>
}
