import assert from 'node:assert/strict'
import { mkdirSync } from 'node:fs'
import { pathToFileURL } from 'node:url'
const { chromium } = process.env.SPM_PLAYWRIGHT_PATH ? await import(pathToFileURL(process.env.SPM_PLAYWRIGHT_PATH).href) : await import('playwright')
const browser = await chromium.launch({ channel: 'msedge', headless: true })
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, timezoneId: 'Asia/Tehran' })
const page = await context.newPage()
const errors = []; page.on('pageerror', error => errors.push(error.message))
const base = process.env.SPM_TEST_URL || 'http://127.0.0.1:5173'
async function go(path) { await page.goto(base + path); await page.locator('main').waitFor() }
async function setDate(label, iso) {
 const date = await page.evaluate(async iso => (await import('/src/lib/dates.ts')).isoToJalali(iso), iso)
 for (const [part,value] of [['روز',1], ['سال',date.year], ['ماه',date.month], ['روز',date.day]]) await page.getByRole('combobox', { name: `${label}: ${part}`, exact: true }).selectOption(String(value))
}
try {
 await go('/')
 const results = await page.evaluate(async () => {
  const { db } = await import('/src/db/db.ts')
  const { projectRepository } = await import('/src/db/repositories/project-repository.ts')
  const { changeProjectStatus } = await import('/src/db/repositories/project-workflow.ts')
  const { activityRepository } = await import('/src/db/repositories/activity-repository.ts')
  const { financeRepository } = await import('/src/db/repositories/finance-repository.ts')
  const { backupRepository } = await import('/src/db/repositories/backup-repository.ts')
  const ensure = (value, message) => { if(!value) throw new Error(message) }
  const rejects = async (call, message) => { let rejected=false; try { await call() } catch { rejected=true } ensure(rejected,message) }
  const customerId = crypto.randomUUID()
  await db.customers.add({ id: customerId, name: 'مشتری گردش‌کار', mobile: '09123456789', createdAt: Date.now(), updatedAt: Date.now() })
  let project = await projectRepository.create({ title: 'پروژه گردش‌کار', customerId, status: 'draft', startDate: '2025-01-01' })
  const { projectItemRepository } = await import('/src/db/repositories/project-item-repository.ts')
  const item = await projectItemRepository.create({ projectId:project.id, title:'خدمت گردش‌کار', unit:'meter', quantity:10, unitPrice:100, pricingType:'PER_METER' })
  const input = { projectItemId:item.id, unit:'meter', projectId: project.id, date: '2025-01-02', title: 'اجرای آزمایشی', quantity: 2 }
  await rejects(() => activityRepository.create(input), 'draft execution should require consent')
  await rejects(() => activityRepository.create({ ...input, quantity: -1 }, { startExecution:true }), 'invalid initial activity must fail')
  ensure((await db.projects.get(project.id)).status === 'draft','failed activity changed status')
  const activity = await activityRepository.create(input, { startExecution: true })
  project = await db.projects.get(project.id)
  ensure(project.status === 'in_progress' && project.executionStartDate === '2025-01-02','start milestone missing')
  await rejects(() => projectRepository.update(project.id, { status:'delivered' }), 'status update bypass')
  const change = async (to,date,reason) => { project = await changeProjectStatus(project.id, { to, effectiveDate:date, expectedStatus:project.status, reason }); return project }
  await rejects(() => change('paused','2025-01-05'), 'pause needs reason')
  await change('paused','2025-01-05','انتظار مصالح')
  await rejects(() => activityRepository.create({ ...input, date:'2025-01-06' }), 'paused execution allowed')
  const late = await activityRepository.create({ ...input, date:'2025-01-03' }, { historical:true, reason:'ثبت دیرهنگام' })
  await rejects(() => activityRepository.create({ ...input, date:'2025-01-07' }, { historical:true, reason:'توضیح' }), 'paused gap accepted')
  await change('in_progress','2025-01-10','ادامه پس از تأمین مصالح')
  await activityRepository.create({ ...input, date:'2025-01-12' })
  await rejects(() => change('completed','2025-01-15'), 'incomplete services require explanation')
  await activityRepository.create({ ...input, date:'2025-01-13', quantity:4 })
  await change('completed','2025-01-15')
  ensure(project.actualEndDate === '2025-01-15','completion date missing')
  await change('delivered','2025-01-17')
  ensure(project.deliveryDate === '2025-01-17','delivery date missing')
  const payment = await financeRepository.createPayment({ customerId, projectId:project.id, date:'2025-01-19', amount:500, method:'cash' })
  ensure(payment.amount === 500,'finance locked after delivery')
  await activityRepository.update(activity.id, { quantity:3 }, { reason:'اصلاح اندازه‌گیری' })
  await rejects(() => activityRepository.update(activity.id, { quantity:4 }), 'unaudited correction allowed')
  await activityRepository.delete(late.id, 'حذف تکرار')
  await rejects(() => change('in_progress','2025-01-20'), 'reopening without reason')
  await change('in_progress','2025-01-20','رفع نقص پس از تحویل')
  ensure(!project.actualEndDate && !project.deliveryDate,'reopening did not clear current completion')
  ensure(project.statusHistory.at(-1).datesBefore.deliveryDate === '2025-01-17','old delivery lost')
  await rejects(() => activityRepository.create({ ...input, date:'2025-01-18' }), 'closed gap accepted')
  await activityRepository.create({ ...input, date:'2025-01-21' })
  await rejects(() => changeProjectStatus(project.id, { to:'paused', expectedStatus:'draft', effectiveDate:'2025-01-22', reason:'تست' }), 'stale transition allowed')
  const historyBefore = JSON.stringify((await db.projects.get(project.id)).statusHistory)
  await rejects(() => projectRepository.update(project.id, { executionStartDate:'2025-01-08' }), 'invalid milestone correction allowed')
  ensure(JSON.stringify((await db.projects.get(project.id)).statusHistory) === historyBefore,'failed update changed history')
  const backup = await backupRepository.export()
  const stored = backup.data.projects.find(row => row.id === project.id)
  ensure(stored.statusHistory.length >= 7 && stored.activityAudit.some(row => row.action === 'delete'),'history absent from backup')
  await rejects(() => projectRepository.create({ title:'legacy forbidden', customerId, status:'active' }), 'new active projects allowed')
  const legacyId=crypto.randomUUID()
  await db.projects.add({ id:legacyId, customerId, title:'فعال قدیمی آزمایشی', status:'active', startDate:'2025-01-01', createdAt:Date.now(), updatedAt:Date.now() })
  await rejects(() => activityRepository.create({ ...input, projectId:legacyId }), 'unreviewed legacy executed')
  let cancelled = await projectRepository.create({ title:'پروژه لغو آزمایشی', customerId, status:'draft', startDate:'2025-01-01', plannedEndDate:'2026-09-05' })
  cancelled = await changeProjectStatus(cancelled.id, { to:'cancelled', expectedStatus:'draft', effectiveDate:'2025-01-02', reason:'عدم توافق' })
  await db.reminders.add({ id:crypto.randomUUID(), title:'پیگیری مالی لغو', projectId:cancelled.id, dueDate:'2026-09-05', status:'open', createdAt:Date.now(), updatedAt:Date.now() })
  return { projectId:project.id, legacyId, cancelledId:cancelled.id }
 })
 console.log('Lifecycle, atomic consent, historical work, audit snapshots, financial independence and legacy protection pass')
 await go('/')
 await page.getByRole('heading',{ name:'بررسی پروژه‌های فعال قدیمی' }).waitFor()
 await page.locator(`a[href="/projects/${results.legacyId}"]`).click()
 await page.getByRole('combobox', { name:'وضعیت جدید', exact:true }).selectOption('planned')
 await setDate('تاریخ تغییر وضعیت','2025-01-02')
 await page.getByRole('button',{ name:'تأیید تغییر وضعیت',exact:true }).click()
 await page.getByText('وضعیت فعلی:', { exact:false }).filter({ hasText:'برنامه‌ریزی‌شده' }).waitFor()
 assert.equal(await page.evaluate(async id => (await (await import('/src/db/db.ts')).db.projects.get(id)).status,results.legacyId),'planned')
 await go(`/projects/${results.projectId}`)
 await page.getByRole('heading',{name:'تاریخچه پروژه',exact:true}).waitFor()
 await page.locator('main').getByText('حذف تکرار', { exact:false }).waitFor()
 await page.getByRole('button',{name:'پیشنهاد تکمیل پروژه',exact:true}).click()
 await setDate('تاریخ تغییر وضعیت','2025-01-22')
 await page.getByRole('button',{name:'تأیید تغییر وضعیت',exact:true}).click()
 await page.getByText('وضعیت فعلی:',{exact:false}).filter({hasText:'تکمیل‌شده'}).waitFor()
 await page.reload()
 await page.getByText('وضعیت فعلی:',{exact:false}).filter({hasText:'تکمیل‌شده'}).waitFor()
 assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth),false)
 mkdirSync('test-results',{recursive:true})
 await page.screenshot({path:'test-results/project-workflow-mobile.png',fullPage:false})
 await go('/calendar')
 assert.equal(await page.getByText('موعد: پروژه لغو آزمایشی',{exact:true}).count(),0)
 await page.getByText('پیگیری مالی لغو',{exact:true}).waitFor()
 assert.deepEqual(errors,[])
 console.log('Legacy review UI, transition form, persisted history, mobile layout and calendar policy pass')
} finally { await browser.close() }
