import assert from 'node:assert/strict'
import {pathToFileURL} from 'node:url'
const {chromium}=await import(pathToFileURL(process.env.SPM_PLAYWRIGHT_PATH).href)
const browser=await chromium.launch({channel:'msedge'}),page=await browser.newPage({viewport:{width:390,height:844}}),base='http://127.0.0.1:5173'
try{
 await page.goto(base)
 await page.evaluate(async()=>{const {db}=await import('/src/db/db.ts'),{backupFixture}=await import('/tests/backup-fixtures.mjs'),d=backupFixture();for(const [name,rows] of Object.entries(d))await db.table(name).bulkPut(rows);for(const [id,status] of [['p2','draft'],['p3','paused'],['p4','delivered'],['p5','planned']])await db.projects.put({...d.projects[0],id,title:id,status,statusHistory:[],activityAudit:[]});for(let i=0;i<35;i++)await db.services.put({...d.services[0],id:'service'+i,name:'خدمت آزمایش '+String(i).padStart(2,'0')})})
 await page.goto(base+'/settings');await page.getByLabel('اولویت اول',{exact:true}).selectOption('draft');await page.waitForFunction(async()=>(await (await import('/src/db/db.ts')).db.appSettings.get('business'))?.dashboardProjectOrder?.[0]==='draft');await page.getByRole('button',{name:'ذخیره تنظیمات',exact:true}).click();await page.getByText('تنظیمات ذخیره شد.',{exact:true}).waitFor();await page.goto(base);await page.locator('[data-dashboard-projects] b').first().waitFor();assert.equal(await page.locator('[data-dashboard-projects] b').first().textContent(),'p2')
 await page.goto(base+'/projects/p1');await page.getByRole('button',{name:/خدمات پروژه و قیمت‌ها/}).click();await page.getByRole('button',{name:'انتخاب از کاتالوگ',exact:true}).click();const list=page.getByLabel('فهرست کاتالوگ خدمات',{exact:true});assert.equal(await list.getByRole('button').count(),37);assert.ok(await list.evaluate(e=>e.scrollHeight>e.clientHeight));await page.getByLabel('جستجوی کاتالوگ خدمات',{exact:true}).fill('آزمایش 34');await list.getByRole('button',{name:'خدمت آزمایش 34',exact:true}).click();assert.equal(await page.getByLabel('عنوان خدمت',{exact:true}).inputValue(),'خدمت آزمایش 34')
 await page.goto(base+'/finance');let receipt=page.locator('article').filter({has:page.getByRole('button',{name:'ویرایش پرداخت',exact:true})}).first();await receipt.getByRole('button',{name:'ویرایش پرداخت',exact:true}).click();await page.getByLabel('مبلغ ویرایش پرداخت',{exact:true}).fill('۱۰۰');await page.getByRole('button',{name:'ذخیره ویرایش پرداخت',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await page.evaluate(async()=>(await (await import('/src/db/db.ts')).db.invoices.get('i1')).status),'paid')
 await receipt.getByRole('button',{name:'ویرایش پرداخت',exact:true}).click();await page.getByLabel('مبلغ ویرایش پرداخت',{exact:true}).fill('40');await page.getByRole('button',{name:'ذخیره ویرایش پرداخت',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await page.evaluate(async()=>(await (await import('/src/db/db.ts')).db.invoices.get('i1')).status),'issued')
 const atomic=await page.evaluate(async()=>{const {db}=await import('/src/db/db.ts'),{savePayment}=await import('/src/db/repositories/payment-mutations.ts');const p=await db.payments.get('pay1');let rejected=false;try{await savePayment({...p,customerId:'missing',amount:999},p.id,p.updatedAt)}catch{rejected=true}return {rejected,amount:(await db.payments.get('pay1')).amount}});assert.deepEqual(atomic,{rejected:true,amount:40})
 page.once('dialog',d=>d.dismiss());await receipt.getByRole('button',{name:'حذف پرداخت',exact:true}).click();assert.equal(await page.evaluate(async()=>await (await import('/src/db/db.ts')).db.payments.count()),1);page.once('dialog',d=>d.accept());await receipt.getByRole('button',{name:'حذف پرداخت',exact:true}).click();await page.waitForFunction(async()=>await (await import('/src/db/db.ts')).db.payments.count()===0)
 await page.evaluate(async()=>{const {db}=await import('/src/db/db.ts');await db.projects.update('p1',{latitude:35.6892,longitude:51.389})});await page.goto(base+'/projects');await page.locator('article').filter({has:page.getByRole('link',{name:'🔧 پروژه پشتیبان',exact:true})}).getByRole('button',{name:'🧭 مسیریابی پروژه',exact:true}).click();await page.getByRole('button',{name:'🧭 انتخاب مسیریاب',exact:true}).click();assert.equal(await page.getByRole('link',{name:'نشان — اپ نصب‌شده',exact:true}).getAttribute('href'),'neshan://?destination=35.689200,51.389000')
 await page.goto(base+'/settings');const mock=await page.evaluate(async()=>{const module=await import('/src/lib/web-push.ts');let blocked=false;try{await module.subscribeToPush()}catch{blocked=true}Object.defineProperty(navigator,'standalone',{value:true,configurable:true});window.pushCalls=[];let subscription=null;Object.defineProperty(window,'Notification',{configurable:true,value:{requestPermission:()=>{window.pushCalls.push('permission');return Promise.resolve('granted')}}});navigator.serviceWorker.getRegistration=async()=>{window.pushCalls.push('registration');return {active:{},pushManager:{getSubscription:async()=>subscription,subscribe:async options=>{window.pushOptions={visible:options.userVisibleOnly,length:options.applicationServerKey.length};window.pushCalls.push('subscribe');subscription={options,toJSON:()=>({endpoint:'https://push.example.test/device',keys:{p256dh:'fixture',auth:'fixture'}}),unsubscribe:async()=>{subscription=null;return true}};return subscription}}}};return blocked});assert.equal(mock,true)
 await page.getByRole('button',{name:'فعال‌سازی اعلان‌ها',exact:true}).click();await page.getByText('اشتراک روی همین دستگاه ذخیره شد.',{exact:true}).waitFor();assert.deepEqual(await page.evaluate(()=>window.pushCalls.slice(0,3)),['permission','registration','subscribe']);assert.deepEqual(await page.evaluate(()=>window.pushOptions),{visible:true,length:65});await page.getByRole('button',{name:'فعال‌سازی اعلان‌ها',exact:true}).click();await page.waitForFunction(()=>window.pushCalls.filter(x=>x==='permission').length===2);assert.equal(await page.evaluate(()=>window.pushCalls.filter(x=>x==='subscribe').length),1)
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'دانلود subscription',exact:true}).click();assert.equal((await download).suggestedFilename(),'lineyar-push-subscription.json');await page.getByRole('button',{name:'غیرفعال‌سازی Web Push',exact:true}).click();await page.getByText('اشتراک غیرفعال شد.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('lineyar-push-subscription-v1')),null)
 console.log('Dashboard ordering, full catalog scroll/search, payment correction/delete, Neshan URL and push subscription passed')
}finally{await browser.close()}
