import {useBusiness} from '@/domain/use-business'
import {db} from '@/db/db'
import {defaultSettings} from '@/domain/media'
import { useEffect,useRef,useState } from 'react'
import { Link,useRouterState } from '@tanstack/react-router'
import guide from '../../docs/user-guide-fa.txt?raw'
const helpTopics:Record<string,{title:string;text:string}>={
 '/':{title:'داشبورد',text:'کارت وضعیت را لمس کنید تا پروژه‌های همان وضعیت باز شوند. خلاصه بالای داشبورد فقط مربوط به امروز است: قرارداد با تاریخ توافق/پروژه امروز، کار اضافه و فاکتور مستقل امروز، منهای دریافتی امروز. مازاد دریافتی امروز به معنی بستانکاری کل مشتری نیست؛ جمع کل در مالی است.'},
 '/projects':{title:'پروژه‌ها',text:'مشتری و مبلغ قرارداد را مشخص کنید. در صفحه پروژه ابتدا گردش کار و سپس تاریخچه دیده می‌شود. خدمات، عکس و موقعیت از بخش‌های بازشونده در دسترس‌اند. تحویل پروژه به معنی تسویه حساب نیست.'},
 '/customers':{title:'مشتریان',text:'مشتری را با نام یا شماره جست‌وجو کنید. لمس شماره، شماره‌گیر را باز می‌کند. در جزئیات مشتری جمع حساب و پروژه‌های او دیده می‌شوند.'},
 '/activities':{title:'فعالیت روزانه',text:'ابتدا گزارش‌ها را مرور کنید. با «فعالیت جدید» فرم باز می‌شود. مقدار و مبلغ اختیاری‌اند. مبلغ فعالیت فقط یادداشت است؛ کار خارج از قرارداد را در کار اضافه ثبت کنید. اصلاح و حذف دلیل می‌خواهند.'},
 '/finance':{title:'حساب و اسناد',text:'طلب پروژه = قرارداد + کار اضافه − تخفیف. فاکتور پروژه دوباره طلب ایجاد نمی‌کند. فاکتور مستقل صادرشده طلب جداست. مانده مثبت بدهکاری و مانده منفی بستانکاری مشتری است. سند را پیش‌نمایش، سپس چاپ یا اشتراک‌گذاری کنید.'},
 '/calendar':{title:'تقویم',text:'روز دارای رویداد را لمس کنید. یک مورد مستقیم باز می‌شود؛ برای چند مورد فهرست انتخابی نمایش داده می‌شود. فعالیت، یادآوری و موعد پروژه با برچسب مشخص‌اند.'},
 '/reminders':{title:'یادآوری‌ها',text:'عنوان، تاریخ و در صورت نیاز پروژه را انتخاب کنید. نام پروژه و مشتری کنار یادآوری دیده می‌شود. انجام‌شده‌کردن، سابقه را حذف نمی‌کند.'},
 '/services':{title:'خدمات',text:'خدمات معمول و قیمت پایه را ثبت کنید. قیمت هر پروژه مستقل است و با ویرایش قیمت پایه عوض نمی‌شود.'},
 '/reports':{title:'گزارش‌ها',text:'جمع حساب‌ها از همان سیاست صفحه مالی پیروی می‌کند. برای بکاپ و بازیابی از لینک تنظیمات استفاده کنید.'},
 '/settings':{title:'تنظیمات',text:'قفل ورود، اطلاعات کسب‌وکار، ظاهر، بکاپ و راهنما اینجاست. بکاپ شامل عکس‌ها و تنظیمات کسب‌وکار است. قفل محلی رمزگذاری اطلاعات نیست و داخل بکاپ منتقل نمی‌شود.'},
 '/help':{title:'راهنمای کامل',text:'راهنمای هر بخش و آموزش کامل برنامه را در این صفحه بخوانید. دکمه ویرایش برای تکمیل متن وجود دارد؛ تغییرات محلی و در بکاپ حفظ می‌شوند.'},
 '/projects/new':{title:'ثبت پروژه',text:'مشتری، عنوان، تاریخ پروژه و مبلغ توافق را وارد کنید. تاریخ توافق مبنای قرارداد در خلاصه مالی روزانه است. موقعیت را از نقشه یا GPS انتخاب کنید و آدرس نوشتاری را برای پلاک و توضیحات نگه دارید.'},
 '/projects/detail':{title:'جزئیات پروژه',text:'گردش کار و تاریخچه در ابتدای صفحه‌اند. حساب پروژه قرارداد، کار اضافه، تخفیف و پرداخت را نشان می‌دهد. گالری عکس‌ها بازشونده است؛ در تصویر کامل عکس‌ها را با کشیدن یا دکمه قبلی/بعدی مرور کنید.'},
 '/customers/new':{title:'ثبت مشتری',text:'نام و شماره مشتری را وارد و ذخیره کنید. شماره در دفترچه مشتریان برای شماره‌گیری در دسترس خواهد بود.'},
 '/customers/detail':{title:'ویرایش مشتری',text:'مشخصات مشتری، پروژه‌ها و حساب او را بررسی کنید. پس از اصلاح ذخیره کنید یا با انصراف بدون ثبت تغییرات برگردید.'},
}
export function PageHelp(){const path=useRouterState({select:s=>s.location.pathname});const topic=Object.entries(helpTopics).filter(([key])=>key!=='/'&&path.startsWith(key)).at(-1)?.[1]??helpTopics['/'];const helpKey=path.startsWith('/projects/')?(path==='/projects/new'?'/projects/new':'/projects/detail'):path.startsWith('/customers/')?(path==='/customers/new'?'/customers/new':'/customers/detail'):Object.keys(helpTopics).filter(key=>key!=='/'&&path.startsWith(key)).at(-1)||'/';const [open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null)
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close()},[open])
 return <><button aria-label="راهنمای این صفحه" className="min-h-11 min-w-11 border rounded-full" onClick={()=>setOpen(true)}>؟</button><dialog ref={dialog} onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)} className="m-auto max-w-lg w-[90vw] rounded-2xl p-5 backdrop:bg-black/40"><h2 className="font-bold">{topic.title}</h2>{open&&<EditableHelp helpKey={helpKey} original={topic.text}/>}<div className="flex gap-4"><button autoFocus className="min-h-11" onClick={()=>setOpen(false)}>بستن راهنما</button><Link to="/help" onClick={()=>setOpen(false)} className="min-h-11 text-indigo-700">راهنمای کامل</Link></div></dialog></>
}
export function HelpPage(){return <div className="space-y-4"><h1 className="text-xl font-bold">راهنمای کامل لاین‌یار</h1>{Object.entries(helpTopics).map(([key,topic])=><details key={key} className="rounded-xl border bg-white p-4"><summary className="min-h-11 cursor-pointer font-bold">{topic.title}</summary><EditableHelp helpKey={key} original={topic.text}/></details>)}<details className="border rounded-xl bg-white p-4"><summary className="min-h-11 cursor-pointer">آموزش کامل تکنسین</summary><EditableHelp helpKey="/full" original={guide}/></details></div>}

function EditableHelp({helpKey,original}:{helpKey:string;original:string}){
 const business=useBusiness(),[editing,setEditing]=useState(false),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const text=business.helpOverrides?.[helpKey]??original
 async function save(){setBusy(true);setError('');try{await db.transaction('rw',db.appSettings,async()=>{const current=await db.appSettings.get('business')||defaultSettings;await db.appSettings.put({...current,helpOverrides:{...current.helpOverrides,[helpKey]:draft},updatedAt:Date.now()})});setEditing(false)}catch{setError('ذخیره راهنما انجام نشد؛ فضای دستگاه را بررسی کنید.')}finally{setBusy(false)}}
 return <div className="my-3 space-y-3">{editing?<><textarea aria-label="متن راهنما" maxLength={200000} className="min-h-64 w-full rounded-xl border p-3 leading-8" value={draft} onChange={e=>setDraft(e.target.value)}/><div className="flex gap-3"><button type="button" disabled={busy} onClick={()=>void save()} className="min-h-11 rounded-lg bg-indigo-700 px-4 text-white">ذخیره راهنما</button><button type="button" disabled={busy} onClick={()=>setEditing(false)} className="min-h-11 px-3">انصراف از ویرایش</button></div></>:<><div className="whitespace-pre-wrap break-words leading-8">{text}</div><button type="button" className="min-h-11 rounded-lg border px-3 text-indigo-700" onClick={()=>{setDraft(text);setEditing(true)}}>✏️ ویرایش راهنما</button></>}{helpKey==='/full'&&<button type="button" className="min-h-11 px-3" onClick={()=>{const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='lineyar-user-guide-fa.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}}>📥 دانلود فایل TXT</button>}<p className="text-xs text-slate-500">متن ویرایش‌شده روی همین دستگاه و داخل بکاپ ذخیره می‌شود.</p>{error&&<p role="alert">{error}</p>}</div>
}
