import {useEffect,useRef,useState} from 'react'
import type {Project} from '@/domain/project/types'
export function ProjectNavigation({project}:{project:Project}){
 const [open,setOpen]=useState(false),[message,setMessage]=useState(''),dialog=useRef<HTMLDialogElement>(null)
 const coordinates=project.latitude!==undefined&&project.longitude!==undefined?`${project.latitude.toFixed(6)}, ${project.longitude.toFixed(6)}`:''
 const destination=coordinates||project.address||''
 const url='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(destination)
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close()},[open])
 return <><button type="button" className="min-h-11 rounded-xl bg-sky-50 px-3 text-sm text-sky-800" onClick={()=>{setMessage('');setOpen(true)}}>🧭 مسیریابی پروژه</button><dialog ref={dialog} onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)} className="m-auto w-[90vw] max-w-md rounded-2xl p-5 backdrop:bg-slate-950/40"><h2 className="font-bold">مسیریابی — {project.title}</h2><p className="my-3 text-sm">{project.address||'آدرس نوشتاری ثبت نشده'}</p>{destination?<><div className="grid grid-cols-2 gap-3"><button disabled={!coordinates} className="min-h-14 rounded-xl border bg-indigo-50 p-3 disabled:opacity-40" onClick={async()=>{try{await navigator.clipboard.writeText(coordinates);setMessage('مختصات کپی شد؛ در جستجوی نشان یا نقشه دلخواه بچسبانید.')}catch{setMessage('کپی خودکار در دسترس نیست؛ مختصات زیر را انتخاب و کپی کنید.')}}}>📋 کپی مختصات</button><button className="min-h-14 rounded-xl border bg-emerald-50 p-3" onClick={async()=>{if(!navigator.share){setMessage('اشتراک در این مرورگر پشتیبانی نمی‌شود؛ از لینک نقشه یا کپی استفاده کنید.');return}try{await navigator.share({title:project.title,text:coordinates||project.address,url})}catch(e){if((e as Error).name!=='AbortError')setMessage('اشتراک انجام نشد؛ مختصات را کپی کنید.')}}}>🧭 مسیریابی و اشتراک</button></div>{coordinates&&<input readOnly aria-label="مختصات قابل کپی" dir="ltr" className="my-3 w-full rounded-lg border p-3 text-center" value={coordinates} onFocus={e=>e.target.select()}/>}<div className="my-3 flex flex-wrap gap-4"><a href={url} target="_blank" rel="noreferrer" className="text-sky-800">بازکردن نقشه</a>{coordinates&&<a href={'https://neshan.org/maps/search/'+encodeURIComponent(coordinates)} target="_blank" rel="noreferrer" className="text-sky-800">بازکردن نشان</a>}</div><p className="text-xs leading-6">قالب مختصات: عرض، طول با ارقام انگلیسی. فهرست اشتراک را گوشی تعیین می‌کند؛ برای نقشه‌های وب که در فهرست نیستند از کپی استفاده کنید.</p></>:<p className="my-4">ابتدا موقعیت یا آدرس پروژه را در ویرایش پروژه ثبت کنید.</p>}<p role="status" className="my-3 text-sm">{message}</p><button autoFocus className="min-h-11 rounded-lg border px-4" onClick={()=>setOpen(false)}>بستن</button></dialog></>
}
