import {useEffect,useRef,useState} from 'react'
import {Link} from '@tanstack/react-router'
import type {Project} from '@/domain/project/types'
export function ProjectNavigation({project}:{project:Project}){
 const [open,setOpen]=useState(false),[maps,setMaps]=useState(false),[message,setMessage]=useState(''),dialog=useRef<HTMLDialogElement>(null)
 const coordinates=Number.isFinite(project.latitude)&&Number.isFinite(project.longitude)?`${project.latitude!.toFixed(6)}, ${project.longitude!.toFixed(6)}`:''
 const destination=coordinates||project.address||'',encoded=encodeURIComponent(destination)
 const url='https://www.google.com/maps/dir/?api=1&destination='+encoded
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close()},[open])
 async function share(){if(!navigator.share){setMessage('اشتراک در این مرورگر پشتیبانی نمی‌شود؛ مسیریاب را مستقیم انتخاب کنید.');return}try{await navigator.share({title:project.title,text:coordinates||project.address,url})}catch(e){if((e as Error).name!=='AbortError')setMessage('اشتراک انجام نشد؛ از انتخاب مسیریاب یا کپی استفاده کنید.')}}
 return <><button type="button" className="min-h-11 rounded-xl bg-sky-50 px-3 text-sm text-sky-800" onClick={()=>{setMessage('');setMaps(false);setOpen(true)}}>🧭 مسیریابی پروژه</button><dialog ref={dialog} onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)} className="m-auto w-[90vw] max-w-md rounded-2xl p-5 backdrop:bg-slate-950/40"><h2 className="font-bold">مسیریابی — {project.title}</h2><p className="my-3 text-sm">{project.address||'آدرس نوشتاری ثبت نشده'}</p>
 <div className="grid grid-cols-2 gap-3"><button type="button" disabled={!coordinates} aria-describedby={!coordinates?'missing-coordinates-'+project.id:undefined} className="min-h-14 rounded-xl border bg-indigo-50 p-3 disabled:opacity-40" onClick={async()=>{try{await navigator.clipboard.writeText(coordinates);setMessage('مختصات کپی شد؛ در جستجوی نشان یا نقشه دلخواه بچسبانید.')}catch{setMessage('کپی خودکار در دسترس نیست؛ مختصات زیر را انتخاب و کپی کنید.')}}}>📋 کپی مختصات</button><button type="button" disabled={!destination} aria-expanded={maps} className="min-h-14 rounded-xl border bg-emerald-50 p-3 disabled:opacity-40" onClick={()=>setMaps(!maps)}>🧭 انتخاب مسیریاب</button></div>
 {!coordinates&&<p id={'missing-coordinates-'+project.id} className="my-3 text-sm text-amber-800">کپی غیرفعال است چون مختصات این پروژه ذخیره نشده. نوشتن آدرس کافی نیست؛ در ویرایش پروژه از نقشه انتخاب کنید یا در محل پروژه موقعیت گوشی را بگیرید و «ذخیره تغییرات» را بزنید.</p>}
 <Link to="/projects/$projectId" params={{projectId:project.id}} onClick={()=>setOpen(false)} className="my-2 inline-block min-h-11 py-2 text-indigo-700">ویرایش موقعیت پروژه</Link>
 {coordinates&&<input readOnly aria-label="مختصات قابل کپی" dir="ltr" className="my-3 w-full rounded-lg border p-3 text-center" value={coordinates} onFocus={e=>e.target.select()}/>}
 {maps&&destination&&<div aria-label="انتخاب نقشه" className="my-3 grid grid-cols-2 gap-3 rounded-xl border p-3"><a href={'https://maps.apple.com/?daddr='+encoded+'&dirflg=d'} className="min-h-11 rounded-lg bg-sky-50 p-3 text-center text-sky-800" target="_blank" rel="noreferrer">Apple Maps</a><a href={url} className="min-h-11 rounded-lg bg-sky-50 p-3 text-center text-sky-800" target="_blank" rel="noreferrer">Google Maps</a>{coordinates&&<a href={'neshan://?destination='+coordinates.replace(/ /g,'')} className="min-h-11 rounded-lg bg-sky-50 p-3 text-center text-sky-800">نشان — اپ نصب‌شده</a>}<a href={'https://neshan.org/maps/search/'+encoded} className="min-h-11 rounded-lg bg-sky-50 p-3 text-center text-sky-800" target="_blank" rel="noreferrer">نشان — نمایش مقصد</a><p className="col-span-2 text-xs leading-6">در نشان پس از نمایش مقصد «مسیریابی» را بزنید. بازشدن اپ نصب‌شده یا نسخه وب به گوشی بستگی دارد.</p></div>}
 {destination&&<button type="button" onClick={()=>void share()} className="min-h-11 rounded-lg border px-3">اشتراک‌گذاری موقعیت</button>}<p className="mt-3 text-xs leading-6">پنجره اشتراک گوشی فهرست مسیریاب‌ها نیست؛ ممکن است هیچ نقشه‌ای در آن نباشد. برای مسیریابی از انتخاب مستقیم بالا یا کپی مختصات استفاده کنید.</p><p role="status" className="my-3 text-sm">{message}</p><button type="button" autoFocus className="min-h-11 rounded-lg border px-4" onClick={()=>setOpen(false)}>بستن</button></dialog></>
}
