import { useEffect, useState } from 'react'
import { backupRepository } from '@/db/repositories/backup-repository'
import { financeRepository } from '@/db/repositories/finance-repository'
import { projectRepository } from '@/db/repositories/project-repository'
import { formatMoney } from '@/lib/money'

export function ReportsPage() {
  const [report, setReport] = useState({ income: 0, payments: 0, outstanding: 0, active: 0 })
  const [message, setMessage] = useState('')
  useEffect(() => { void (async () => { const [invoices, payments, projects] = await Promise.all([financeRepository.getInvoices(), financeRepository.getPayments(), projectRepository.getAll()]); const income = invoices.filter((item) => item.status !== 'void').reduce((sum, item) => sum + item.total, 0); const received = payments.reduce((sum, item) => sum + item.amount, 0); setReport({ income, payments: received, outstanding: income - received, active: projects.filter((item) => item.status === 'active').length }) })() }, [])
  async function exportBackup() { const backup = await backupRepository.export(); const url = URL.createObjectURL(new Blob([JSON.stringify(backup, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `service-project-manager-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); setMessage('بکاپ با موفقیت دانلود شد') }
  async function importBackup(file?: File) { if (!file) return; try { const data: unknown = JSON.parse(await file.text()); if (!backupRepository.validate(data)) throw new Error(); if (!confirm('همه داده‌های فعلی با این بکاپ جایگزین شوند؟')) return; await backupRepository.import(data); setMessage('بکاپ بازیابی شد؛ صفحه را تازه کنید') } catch { setMessage('فایل بکاپ معتبر نیست') } }
  const cards = [['درآمد فاکتورهای معتبر', report.income, 'bg-indigo-600'], ['دریافتی‌ها', report.payments, 'bg-emerald-600'], ['ماندهٔ قابل دریافت', report.outstanding, 'bg-amber-500'], ['پروژه‌های فعال', report.active, 'bg-slate-700']]
  return <div className="max-w-5xl space-y-6"><div><h2 className="text-xl font-bold">گزارش‌ها و بکاپ</h2><p className="text-sm text-slate-500">گزارش‌های واقعی بر پایهٔ داده‌های ذخیره‌شده در دستگاه شما</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([title, value, color]) => <div key={title} className={`${color} rounded-2xl p-5 text-white shadow-sm`}><p className="text-xs text-white/75">{title}</p><p className="mt-3 text-xl font-bold">{typeof value === 'number' && title !== 'پروژه‌های فعال' ? formatMoney(value) : value}</p></div>)}</div><section className="rounded-2xl border bg-white p-5 space-y-4"><div><h3 className="font-bold">پشتیبان‌گیری داده‌ها</h3><p className="mt-1 text-sm text-slate-500">فایل JSON شامل همهٔ مشتری‌ها، پروژه‌ها، فعالیت‌ها و اسناد مالی است.</p></div><div className="flex flex-wrap gap-3"><button onClick={exportBackup} className="rounded-lg bg-slate-800 px-4 py-2 text-sm text-white">دانلود بکاپ</button><label className="cursor-pointer rounded-lg border px-4 py-2 text-sm">بازیابی بکاپ<input type="file" accept="application/json,.json" className="hidden" onChange={(event) => void importBackup(event.target.files?.[0])}/></label></div>{message && <p className="rounded-lg bg-slate-50 p-3 text-sm">{message}</p>}</section></div>
}
