import { JalaliDatePicker } from '@/components/jalali-date-picker'
import { toISODate, formatDateFa } from '@/lib/dates'
import { serviceUnits } from '@/domain/service/helpers'
import { useEffect, useMemo, useState } from 'react'
import type { ID, Unit } from '@/types'
import type { ProjectChange } from '@/domain/project-change/types'
import type { Material } from '@/domain/material/types'
import type { Expense } from '@/domain/expense/types'
import { projectChangeRepository } from '@/db/repositories/project-change-repository'
import { materialRepository } from '@/db/repositories/material-repository'
import { expenseRepository } from '@/db/repositories/expense-repository'
import { formatMoney } from '@/lib/money'

export function FinancialPanel({ projectId, contractAmount }: { projectId: ID; contractAmount: number }) {
  const [changes, setChanges] = useState<ProjectChange[]>([]); const [materials, setMaterials] = useState<Material[]>([]); const [expenses, setExpenses] = useState<Expense[]>([])
  const [kind, setKind] = useState<'change'|'material'|'expense'|null>(null)
  const load = async () => { const [c,m,e] = await Promise.all([projectChangeRepository.getByProjectId(projectId),materialRepository.getByProjectId(projectId),expenseRepository.getByProjectId(projectId)]); setChanges(c);setMaterials(m);setExpenses(e) }
  useEffect(() => { load() }, [projectId])
  const totals = useMemo(() => ({ changes: changes.reduce((s,x)=>s+x.amount,0), expenses: expenses.reduce((s,x)=>s+x.amount,0) + materials.filter(x=>x.source==='contractor').reduce((s,x)=>s+x.cost,0), receivable: contractAmount + changes.reduce((s,x)=>s+x.amount,0) }), [changes,materials,expenses,contractAmount])
  const [date, setDate] = useState(toISODate)
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f=new FormData(e.currentTarget); const title=String(f.get('title')||''); if(!title || saving)return; setSaving(true); setError(''); try { if(kind==='change')await projectChangeRepository.create({projectId,title,amount:Number(f.get('amount')),date:String(f.get('date')),note:String(f.get('note')||'')}); if(kind==='expense')await expenseRepository.create({projectId,title,amount:Number(f.get('amount')),date:String(f.get('date')),note:String(f.get('note')||'')}); if(kind==='material')await materialRepository.create({projectId,title,date:String(f.get('date')),quantity:Number(f.get('quantity')),unit:String(f.get('unit')) as Unit,source:String(f.get('source')) as 'customer'|'contractor',cost:Number(f.get('cost'))}); setKind(null);await load() } catch { setError('ذخیره ناموفق بود؛ اطلاعات را بررسی کنید.') } finally { setSaving(false) } }
  return <section className="space-y-4"><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-emerald-50 p-4"><p className="text-xs text-emerald-700">کار اضافه</p><b>{formatMoney(totals.changes)}</b></div><div className="rounded-xl bg-rose-50 p-4"><p className="text-xs text-rose-700">هزینه‌های ثبت‌شده</p><b>{formatMoney(totals.expenses)}</b></div></div><div className="flex gap-2"><button onClick={()=>{setDate(toISODate());setKind('change')}} className="rounded-lg bg-slate-800 px-3 py-2 text-sm text-white">کار اضافه</button><button onClick={()=>{setDate(toISODate());setKind('material')}} className="rounded-lg border px-3 py-2 text-sm">مصالح</button><button onClick={()=>{setDate(toISODate());setKind('expense')}} className="rounded-lg border px-3 py-2 text-sm">هزینه</button></div>{kind&&<form onSubmit={submit} className="grid gap-3 rounded-xl border bg-slate-50 p-4"><b>{kind==='change'?'ثبت کار اضافه':kind==='material'?'ثبت مصالح':'ثبت هزینه'}</b><input required name="title" placeholder="شرح" className="rounded-lg border p-2"/>{kind==='material'?<><div className="grid grid-cols-2 gap-2"><input required name="quantity" type="number" min="0" placeholder="مقدار" className="rounded-lg border p-2"/><select name="unit" aria-label="واحد مصالح" className="rounded-lg border p-2">{serviceUnits.map((unit) => <option key={unit.value} value={unit.value}>{unit.label}</option>)}</select></div><select name="source" className="rounded-lg border p-2"><option value="customer">تهیه مشتری</option><option value="contractor">تهیه پیمانکار</option></select><input name="cost" type="number" min="0" defaultValue="0" placeholder="هزینه پیمانکار" className="rounded-lg border p-2"/></>:<><input required name="amount" type="number" min="0" placeholder="مبلغ تومان" className="rounded-lg border p-2"/><input name="note" placeholder="یادداشت" className="rounded-lg border p-2"/></>}<div><p className="text-sm">تاریخ (شمسی)</p><JalaliDatePicker name="date" value={date} onChange={setDate} disabled={saving} /></div><button disabled={saving} className="rounded-lg bg-emerald-600 p-2 text-white">ذخیره</button></form>}<div role="alert" className="text-sm text-rose-700">{error}</div><div className="space-y-2 text-sm">{changes.map(x=><p key={x.id}>کار اضافه: {x.title} · {formatDateFa(x.date)} — {formatMoney(x.amount)}</p>)}{materials.map(x=><p key={x.id}>مصالح: {x.title} · {formatDateFa(x.date || toISODate(new Date(x.createdAt)))} ({x.quantity} {x.unit}) — {x.source==='customer'?'مشتری':'پیمانکار'}</p>)}{expenses.map(x=><p key={x.id}>هزینه: {x.title} · {formatDateFa(x.date)} — {formatMoney(x.amount)}</p>)}</div></section>
}
