import { useEffect,useState } from 'react'
import { liveQuery } from 'dexie'
import { db } from '@/db/db'
import { compressImage,type Photo } from '@/domain/media'
import { toISODate,formatDateFa } from '@/lib/dates'
import { JalaliDatePicker } from '@/components/jalali-date-picker'
export function ProjectPhotos({projectId}:{projectId:string}){
 const [photos,setPhotos]=useState<Photo[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Photo|null>(null),[date,setDate]=useState(toISODate),[title,setTitle]=useState('')
 useEffect(()=>{const s=liveQuery(()=>db.photos.where('projectId').equals(projectId).toArray()).subscribe({next:setPhotos,error:()=>setError('خواندن عکس‌ها ناموفق بود.')});return()=>s.unsubscribe()},[projectId])
 async function upload(file:File){setBusy(true);setError('');try{const image=await compressImage(file);await db.transaction('rw',db.projects,db.photos,async()=>{if(!await db.projects.get(projectId))throw Error('پروژه یافت نشد.');await db.photos.add({...image,id:crypto.randomUUID(),projectId,date,title:title.trim()||file.name,createdAt:Date.now(),updatedAt:Date.now()})});setTitle('')}catch(e){setError(e instanceof Error&&e.name==='QuotaExceededError'?'فضای دستگاه کافی نیست؛ عکس ذخیره نشد.':String(e))}finally{setBusy(false)}}
 return <details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer min-h-11 font-bold">عکس‌های پروژه ({photos.length.toLocaleString('fa-IR')})</summary><div className="space-y-3"><input aria-label="شرح عکس" placeholder="شرح عکس" className="w-full border rounded-lg p-2" value={title} onChange={e=>setTitle(e.target.value)}/><JalaliDatePicker label="تاریخ عکس" value={date} onChange={setDate}/><label className="block">افزودن عکس فشرده (تا ۲۰ مگابایت)<input aria-label="افزودن عکس" disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void upload(file)}}/></label><p className="text-xs">عکس‌ها فقط در همین دستگاه و بکاپ کامل ذخیره می‌شوند.</p>{busy&&<p role="status">در حال فشرده‌سازی…</p>}{error&&<p role="alert">{error}</p>}<div className="grid grid-cols-2 gap-3">{photos.map(photo=><article key={photo.id}><button onClick={()=>setSelected(photo)} className="w-full"><img src={photo.thumbnail} alt={photo.title} className="w-full rounded-lg aspect-square object-cover"/><span className="break-words">{photo.title}</span></button><p className="text-xs">{formatDateFa(photo.date)} · {Math.ceil(photo.bytes/1024)} KB</p><button disabled={busy} className="min-h-11 text-rose-700" onClick={async()=>{if(!confirm('عکس حذف شود؟ برای بازیابی به بکاپ نیاز دارید.'))return;try{await db.photos.delete(photo.id)}catch{setError('حذف عکس انجام نشد.')}}}>حذف عکس</button></article>)}</div></div>{selected&&<div role="dialog" aria-modal="true" aria-label="تصویر کامل" className="fixed inset-0 z-50 bg-slate-950/90 p-4 grid place-content-center" onClick={()=>setSelected(null)}><button autoFocus className="text-white min-h-11" onClick={()=>setSelected(null)} onKeyDown={e=>{if(e.key==='Escape')setSelected(null)}}>بستن تصویر</button><img src={selected.dataUrl} alt={selected.title} className="max-h-[80vh] max-w-full"/></div>}</details>
}
