import { useState } from 'react'
import { projectRepository } from '@/db/repositories/project-repository'
import type { Project } from '@/domain/project/types'
export function ProjectLocation({project,onChange}:{project:Project;onChange:(project:Project)=>void}){
 const [lat,setLat]=useState(project.latitude===undefined?'':String(project.latitude)),[lng,setLng]=useState(project.longitude===undefined?'':String(project.longitude)),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const query=project.latitude!==undefined&&project.longitude!==undefined?`${project.latitude},${project.longitude}`:project.address
 async function save(){setError('');setBusy(true);try{if(!lat.trim()||!lng.trim()||!Number.isFinite(Number(lat))||!Number.isFinite(Number(lng))||Math.abs(Number(lat))>90||Math.abs(Number(lng))>180)throw Error('عرض بین ۹۰- تا ۹۰ و طول بین ۱۸۰- تا ۱۸۰ وارد کنید.');onChange(await projectRepository.update(project.id,{latitude:Number(lat),longitude:Number(lng)}))}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <details className="rounded-xl border bg-white p-4"><summary className="min-h-11 cursor-pointer font-bold">موقعیت پروژه</summary><div className="space-y-3"><p>{project.address||'آدرس ثبت نشده'}</p>{query&&<div className="flex flex-wrap gap-3"><a className="min-h-11 text-indigo-700" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`} target="_blank" rel="noreferrer">باز کردن نقشه</a><a className="min-h-11 text-indigo-700" href={`geo:${project.latitude??0},${project.longitude??0}?q=${encodeURIComponent(query)}`}>برنامه نقشه گوشی</a><a className="min-h-11 text-indigo-700" href={`https://maps.apple.com/?q=${encodeURIComponent(query)}`} target="_blank" rel="noreferrer">Apple Maps</a></div>}<p className="text-xs">نمایش انتخاب‌گر اپ نقشه به سیستم‌عامل گوشی بستگی دارد.</p><label className="block">عرض جغرافیایی<input className="w-full rounded border p-2" aria-label="عرض جغرافیایی" value={lat} onChange={e=>setLat(e.target.value)} inputMode="decimal"/></label><label className="block">طول جغرافیایی<input className="w-full rounded border p-2" aria-label="طول جغرافیایی" value={lng} onChange={e=>setLng(e.target.value)} inputMode="decimal"/></label><button disabled={busy} className="min-h-11 border rounded px-3" onClick={()=>{if(!navigator.geolocation){setError('مکان‌یابی پشتیبانی نمی‌شود.');return}navigator.geolocation.getCurrentPosition(pos=>{setLat(String(pos.coords.latitude));setLng(String(pos.coords.longitude))},()=>setError('مکان دریافت نشد؛ مختصات را دستی وارد کنید.'),{timeout:15000})}}>دریافت موقعیت فعلی من</button><button disabled={busy} className="min-h-11 border rounded px-3" onClick={()=>void save()}>ذخیره موقعیت</button>{error&&<p role="alert">{error}</p>}</div></details>
}
