import {PhotoViewer} from '@/components/photo-viewer'
import {useRouterState} from '@tanstack/react-router'
import { useEffect,useRef,useState } from 'react'
import { liveQuery } from 'dexie'
import { db } from '@/db/db'
import { compressImage,type Photo } from '@/domain/media'
import { toISODate,formatDateFa } from '@/lib/dates'
import { JalaliDatePicker } from '@/components/jalali-date-picker'
export function ProjectPhotos({projectId,standalone=false}:{projectId:string;standalone?:boolean}){
 const hash=useRouterState({select:s=>s.location.hash});const section=useRef<HTMLDetailsElement>(null)
 useEffect(()=>{if(hash==='photos'){section.current!.open=true;section.current?.scrollIntoView({block:'start'})}},[hash])
 const running=useRef(false)
 const [progress,setProgress]=useState('')
 const [photos,setPhotos]=useState<Photo[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Photo|null>(null),[date,setDate]=useState(toISODate),[title,setTitle]=useState('')
 useEffect(()=>{const s=liveQuery(()=>db.photos.where('projectId').equals(projectId).toArray()).subscribe({next:setPhotos,error:()=>setError('خواندن عکس‌ها ناموفق بود.')});return()=>s.unsubscribe()},[projectId])
 async function upload(files:File[]){
  if(running.current)return;running.current=true;setBusy(true);setError('');const failures:string[]=[];let saved=0;const caption=title.trim(),photoDate=date
  try{for(let index=0;index<files.length;index++){const file=files[index];setProgress('در حال ذخیره عکس '+(index+1).toLocaleString('fa-IR')+' از '+files.length.toLocaleString('fa-IR'));try{const image=await compressImage(file);await db.transaction('rw',db.projects,db.photos,async()=>{if(!await db.projects.get(projectId))throw Error('پروژه یافت نشد.');await db.photos.add({...image,id:crypto.randomUUID(),projectId,date:photoDate,title:caption?(files.length>1?caption+' — '+file.name:caption):file.name,createdAt:Date.now(),updatedAt:Date.now()})});saved++}catch(e){failures.push(file.name+': '+(e instanceof Error&&e.name==='QuotaExceededError'?'فضای دستگاه کافی نیست؛ این عکس ذخیره نشد.':e instanceof Error?e.message:'ذخیره انجام نشد.'))}}
   if(saved)setTitle('');setError(failures.join('\n'));setProgress(saved.toLocaleString('fa-IR')+' عکس ذخیره شد'+(failures.length?'؛ '+failures.length.toLocaleString('fa-IR')+' عکس ناموفق بود.':'.'))
  }finally{setBusy(false);running.current=false}
 }
 return <details open={standalone||undefined} ref={section} id="photos" style={{scrollMarginTop:90}} className="rounded-xl border bg-white p-4"><summary className={standalone?"hidden":"cursor-pointer min-h-11 font-bold"}>عکس‌های پروژه ({photos.length.toLocaleString('fa-IR')})</summary><div className="flex flex-col gap-3"><details open={standalone?undefined:true} className={standalone?"order-2 rounded-xl border p-3":"contents"}><summary className={standalone?"min-h-11 cursor-pointer":"hidden"}>📥 افزودن عکس جدید</summary><div className="space-y-3"><input aria-label="شرح عکس" placeholder="شرح عکس" className="w-full border rounded-lg p-2" value={title} onChange={e=>setTitle(e.target.value)}/><JalaliDatePicker label="تاریخ عکس" value={date} onChange={setDate}/><label className="block">افزودن عکس فشرده (تا ۲۰ مگابایت)<input aria-label="افزودن عکس" disabled={busy} type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(files.length)void upload(files)}}/></label></div></details><p className="order-3 text-xs">عکس‌ها فقط در همین دستگاه و بکاپ کامل ذخیره می‌شوند.</p>{progress&&<p role="status">{progress}</p>}{error&&<p role="alert" className="whitespace-pre-wrap break-words">{error}</p>}<div className="order-1 grid grid-cols-2 gap-3">{!photos.length&&<p className="col-span-2 text-sm text-slate-500">هنوز عکسی ثبت نشده؛ از «افزودن عکس جدید» استفاده کنید.</p>}{photos.map(photo=><article key={photo.id}><button aria-label={"نمایش "+photo.title} onClick={()=>setSelected(photo)} className="w-full"><img src={photo.thumbnail} alt={photo.title} className="w-full rounded-lg aspect-square object-cover"/><span className="break-words">{photo.title}</span></button><p className="text-xs">{formatDateFa(photo.date)} · {Math.ceil(photo.bytes/1024)} KB</p><button disabled={busy} className="min-h-11 text-rose-700" onClick={async()=>{if(!confirm('عکس حذف شود؟ برای بازیابی به بکاپ نیاز دارید.'))return;try{await db.photos.delete(photo.id)}catch{setError('حذف عکس انجام نشد.')}}}>حذف عکس</button></article>)}</div></div>{selected&&<PhotoViewer photos={photos} initialId={selected.id} onClose={()=>setSelected(null)}/>}</details>
}
